### ISSUE TITLE
Law page

### ISSUE THREAD

**Issue by emilcieslar** [emilcieslar/tangowithdjango#12]
What I need in context_dict:
1. voted_for - A number of users that voted for a law
2. voted_against - A number of users that voted against a law
2. upcoming - True or False variable whether a law is upcoming or passed parliament
3. msps - dictionary of msps connected to the user that is logged in (this dict will be empty if user is not logged in)
4. comments_number - number of comments posted
5. comments - all comments objects
6. commentForm - a form for a comment
7. law_result - result of a law (in a user friendly format, not 0 or 1 or whatever)
8. law - an actual law object

**Comment by jamesrferguson** [comment]
1,2& 3 added - need to pip install requests

**Comment by Cristinapisi** [comment]
Read your issue after refactoring views. This is what is different from what you asked for:
upcoming is a string: "Past" or "Upcoming"
law_result is 0 or 1 or whatever, but I added the necessary if statements in the templates that print it right. I did this because I think it is easier to have some if's in the template than to try to manipulate strings for the ML bit. Maybe we won't need to, tbh, not sure where that should be placed at the moment. Also, it makes it faster at the backend side. Also, since the result is already in the law, it felt redundant to pass another object with the same information to the template. This is different from the ''upcoming" which is necessary as you cannot manipulate date objects in the template.

comment_form has not been tested yet.

I will close this issue now since I believe most functionality has been acquired. If anyone doesn't agree, feel free to reopen it.
